### ISSUE TITLE
Revenir sur la page de choix du point plutôt que le listing des quests

### ISSUE THREAD

**Issue by wadouk** [wadouk/od2osm#15]

**Comment by Bibi56** [comment]
Soyons fous, comme MapRoulette, proposer le lien suivant directement (le plus proche, au hasard...) en tenant compte des pages déjà demandées par d'autres pour limiter les risques de conflits.

**Comment by wadouk** [comment]
Oui plus évolué, serait bien d'être amené sur le suivant au hasard. Me demande juste comment faire ce haut hasard. Pour un début revenir sur la liste, pour plus tard, avoir un "point suivant"

**Comment by Bibi56** [comment]
Peut-être https://github.com/osmlab/maproulette3 ? Je ne sais si le choix du suivant (aléatoire, à côté géographiquement, suivant dans la liste) se fait côté client ou plus probablement côté serveur mais ici c'est en NodeJS ;-).
