### ISSUE TITLE
Mes premiers retours en vrac

### ISSUE THREAD

**Issue by overflorian** [wadouk/od2osm#2]
Hey, très cool ce nouvel outil, j'ai l'idée en tête pour un outil similaire depuis quelques temps déjà, 'y-a-qu'à-fau-kon' maintenant ;)
bref, content d'aider si besoin. Désolé, je commence par un retour en vrac en espérant que ça t'aide à démarrer.

J'ai aidé @panieravide a faire https://pic4review.pavie.info donc ma première suggestion c'est de s'inspirer du tunnel de contribution qui me semble à priori assez similaire à ton outil :
1. voir les quêtes dispos (s'inspirer de la page https://pic4review.pavie.info/#/missions)
2. en choisir une
3. traiter chaque point un par un
4. une fois traité, un nouveau point apparaît sans plus de formalité
5. on a un suivi du travail réalisé : stats / gamification / taux de complétude
dans pic4review il y a 3 onglets dédiés qui me paraissent ceux qui iront bien sur ton outil :
![image](https://user-images.githubusercontent.com/11553211/82048788-8aca9280-96b5-11ea-894c-10dbfb2fa9ee.png)

Après mon premier test de ton outil, voici mes premiers retours :
- la dynamique globale est la bonne
- tu devrais rajouter des boutons d'avancement pour avancer / reculer dans le process
- je n'ai pas compris l'intérêt des statuts de "création" et de "modification" : actuellement j'ai "créé" 2 lieux mais ils n'apparaissent pas dans OSM donc j'imagine que c'est un état intermédiaire où tu peux "réserver" un POI pour bosser dessus, c'est ça ?
Quel est l'intérêt d'un tel statut ? Ne peut-on pas tout simplement s'en passer ? On pourrait garder 2 états : à faire / fait
- Est-ce que la conflation prend bien en compte les variantes d'orthographe ? Exemple : Biocoop / biocoop / biocop / bicop
- cool l'outil qui permet d'élargir la zone de conflation
- je n'ai pas compris à quoi servent les boutons "plutôt OD", "plutôt OSM" ni même les boutons "OD" et "OSM" sur chaque ligne; je n'ai pas non plus compris pourquoi ces boutons sont grisés
- les numéros de contact:phone devraient mieux respecter le format international, sans espaces
- je n'avais pas compris que la carte permettait de replacer le POI : il faut l'indiquer car pour l'instant il est écrit 'le point à trouver est ici'
- dans le récap juste avant de contribuer, au lieu d'indiquer les coordonnées, il serait mieux de ré-afficher la carte

A ta dispo pour continuer à tester les versions ultérieures de l'outil ;)
++

**Comment by wadouk** [comment]
Cool merci ! J'ai un (autre) retour ! Le premier en issue ! (content)

> - tu devrais rajouter des boutons d'avancement pour avancer / reculer dans le process

J'ai essayé de simplifier au maximum mais le tunnel de contrib me semble de plus en plus incontournable. Je vais m'inspirer de la manière de pic4review. J'ai imaginé de choisir le prochain point automatiquement mais je compte sur l'aléatoire humain pour l'instant. Cela est intéressant mais pas indispensable pour la première version. Même si on ne pourra pas toujours avancer ou reculer ou alors au risque de perdre des choses déjà faites. Quel usage cherches-tu avec ces notions ? Matérialiser le processus OK, se balader dedans, je sais pas trop.

> - je n'ai pas compris l'intérêt des statuts de "création" et de "modification"

Il y a deux choses différentes dans ce que tu questionnes, l'état du point opendata vs OSM, et l'état dans le tunnel od2osm. 

Le point est à faire, en cours, fait du point de vue od2osm. 

Quand on en est à "en cours" ou peut soit créer le point dans OSM soit le modifier. C'est une forme de réservation sur un bug probable futur : 2 contributeurs prennent le même point et commencent à le modifier tous les deux, tout le changeset risque d'être rejeté et je n'ai aucune idée de comment concilier à cette étape. L'idée est plus tard : notifier si un point est déjà pris / fait par un autre alors qu'on est plus sur la liste. Mais ce sera un problème de "riche" quand l'outil sera beaucoup utilisé.

> - cool l'outil qui permet d'élargir la zone de conflation

Je me suis demandé entre le champs numérique et juste des boutons genre 20m 50m 100m mais au delà ça perd du sens, et autant déplacer le point.

> - les boutons "plutôt OD", "plutôt OSM"

Les boutons OSM/OD n'ont effectivement pas de sens en création d'un point : il sont là pour contrôler par clic la source d'information "principale".
exemple en modification: si un Tag T vaux "a" en OD et "B" en OSM, les boutons du haut applique la stratégie pour tous, ou par ligne. En cliquant sur OD (OpenData) la valeur résultante sera "a" en cliquant su OSM la valeur finale sera "B".
Ils sont grisés parce que déjà à la valeur de la colonne.
Pour voir leur utilité, le cas de test est le suivant : sur l'environnement de dev, reprendre un point déjà créé par od2osm (plus facile à retrouver), modifier ces tags pour qu'ils ne correspondent plus à l'OD, reprendre dans od2osm, la liste des tags est alors fusionné, chaque colonne est remplie avec les valeurs de la source, les boutons permettent de passer de l'une à l'autre.

> - le format des phones 

je comptais les reformater effectivement, mais je croyais que les espaces c'était bien. Je vais relire le wiki.

> - variantes d'orthographe

La conflation ne prends en compte les orthographe proche. Je note qu'il faudrait pouvoir débrailler la recherche et laisser la main sur quoi rechercher.

> - déplacement du marqueur

Il y a un paquet de texte au dessus de la carte avec la petite phrase "Vous pouvez déplacer le marqueur OpenData". est c'est 'le point à trouver est **par** ici'

Comment verrais tu plus l'indiquer ? Je voulais mettre un marqueur différent mais pas trouver de solution leaflet qui me satisfasse (avoir des nombres, des couleurs ... bref du svg) . Si l'OD et l'OSM sont trop proches on ne vois qu'un marqueur. Un `cursor: move` sur le marqeur ? mais il faut s'approcher du marqueur pour le savoir ...

> - au lieu d'indiquer les coordonnées, il serait mieux de ré-afficher la carte

A quoi servirait la carte à cette étape ? Les coordonnées ne sont pas utile non plus. Sur ID, Osmose, JOSM ou ne revoit pas le contenu du changeset, on ne peut même pas modifier son contenu. Pour le debug, j'ai préféré revoir ce qu'il y avait dedans mais je sais pas si je vais le laisser.

**Comment by wadouk** [comment]
ps : je note aussi les remarques sur la partie statistique et gamification. c'est aussi pour ça que j'ai préféré m'embêter avec oauth pour que chacun contribue en son nom.

**Comment by wadouk** [comment]
ps2: mais en fait le name n'entre pas dans la conflation, il est affiché pour informer le contributeur ce qu'il doit chercher, mais seul le tag principal (shop ou amenity) et les coordonnées sont utilisées. Donc pas de problème de typo entre biocop biocoop ...

**Comment by pyrog** [comment]
>>le format des phones

>je comptais les reformater effectivement, mais je croyais que les espaces c'était bien. Je vais relire le wiki.

Voir mes commentaires https://github.com/wadouk/od2osm/issues/10#issuecomment-633123038

**Comment by wadouk** [comment]
Les remarques ici ont été ventilées dans les différentes issues
